controllers:
    resource: ../src/Controller/
    type: attribute

route_accueil:
    path: /accueil
    controller: App\Controller\UtilisateurController::index

cours_lister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister