controllers:
    resource: ../src/Controller/
    type: attribute

route_accueil:
    path: /accueil
    controller: App\Controller\UtilisateurController::index

mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\EleveController::ML

#Eleve

route_Eleve:
    path: /eleve/
    controller: App\Controller\EleveController::index

EleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve


#Route Instrument

instrumentListerType:
    path: /instrument/listerType
    controller: App\Controller\InstrumentController::listerTypeInstrument

instrumentListerTypeByID:
    path: /instrument/listerType/{id}
    controller: App\Controller\InstrumentController::instrumentListerTypeByID

instrumentConsulterType:
    path: /instrument/consulterType/{id}
    controller: App\Controller\InstrumentController::consulterTypeInstrument

instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument

instrumentConsulterMaintenance:
    path: /instrument/consulterMaintenance/{id}
    controller: App\Controller\InstrumentController::consulterMaintenance


#Classe Instrument
classeInstrumentLister:
    path: /classeInstrument/lister
    controller: App\Controller\ClasseInstrumentController::lister


#Cours

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister

coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours

# Login 
app_login:
    path: /login/index
    controller: App\Controller\LoginController::index

Inscription:
    path: /register/inscription
    controller: App\Controller\RegistrationController::register

    # config/routes.yaml
app_logout:
    path: /logout
    methods: GET

#Professeur :
ProfesseurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterProfesseur

