controllers:
    resource: ../src/Controller/
    type: attribute

route_accueil:
    path: /accueil
    controller: App\Controller\UtilisateurController::index

instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstrument