controllers:
    resource: ../src/Controller/
    type: attribute

route_accueil:
    path: /accueil
    controller: App\Controller\UtilisateurController::index

mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\EleveController::ML

politiqueCo:
    path: /politiqueDeConfidentialite
    controller: App\Controller\EleveController::PC


#Eleve

EleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve

EleveSupprimer:
    path: /eleve/supprimer/{id}
    controller: App\Controller\EleveController::supprimerEleve

eleveModifier:
    path: /eleve/modifier/{id}
    controller: App\Controller\EleveController::modifier

#Route Instrument

instrumentListerType:
    path: /instrument/listerType
    controller: App\Controller\InstrumentController::listerTypeInstrument

instrumentListerTypeByID:
    path: /instrument/listerType/{id}
    controller: App\Controller\InstrumentController::instrumentListerTypeByID

instrumentConsulterType:
    path: /instrument/consulterType/{id}
    controller: App\Controller\InstrumentController::consulterTypeInstrument

instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument

instrumentConsulterMaintenance:
    path: /instrument/consulterMaintenance/{id}
    controller: App\Controller\InstrumentController::consulterMaintenance

instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouterInstrument


instrumentSupprimer:
    path: /instrument/supprimer/{id}
    controller: App\Controller\InstrumentController::supprimerInstrument

instrumentModifier:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifierInstrument


#Classe Instrument

classeInstrumentLister:
    path: /classeInstrument/lister
    controller: App\Controller\ClasseInstrumentController::lister

#Responsable
ResponsableConsulter:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulter

responsableModifier:
    path: /responsable/modifier/{id}
    controller: App\Controller\ResponsableController::modifier


#Cours
coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister

coursSupprimer:
    path: /cours/supprimer/{id}
    controller: App\Controller\CoursController::supprimer

coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours

coursAjouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouterCours

coursModifier:
    path: /cours/modifier/{id}
    controller: App\Controller\CoursController::modifierCours

EleveCoursSupprimer:
    path: /cours/supprimer/{id}
    controller: App\Controller\CoursController::supprimerCoursEleve

EleveCoursAjouter:
    path: /cours/eleve/ajouter
    controller: App\Controller\CoursController::ajouterCoursEleve

# Login

app_login:
    path: /login/index
    controller: App\Controller\LoginController::index

Inscription:
    path: /register/inscription
    controller: App\Controller\RegistrationController::register

InscriptionEleve:
    path: /eleve/inscription
    controller: App\Controller\RegistrationEleveController::register


    # config/routes.yaml

app_logout:
    path: /logout
    methods: GET


#Professeur :

ProfesseurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterProfesseur

professeurModifier:
    path: /professeur/modifier/{id}
    controller: App\Controller\ProfesseurController::modifier



#Emprunt
empruntLister:
    path: /emprunt/lister/
    controller: App\Controller\EmpruntController::lister

empruntConsulter:
    path: /emprunt/consulter/{id}
    controller: App\Controller\EmpruntController::consulter

empruntAjouter:
    path: /emprunt/ajouter/{id}
    controller: App\Controller\EmpruntController::ajouter

empruntSupprimer:
    path: /emprunt/supprimer/{id}
    controller: App\Controller\EmpruntController::supprimer

#Connecté :
ConnectéConsulter:
    path: /connecte/consulter/{mail}
    controller: App\Controller\UtilisateurController::consulter

# Paiement
payer:
    path: /payement/{id}
    controller: App\Controller\PaiementController::pagePaiement