controllers:
    resource: ../src/Controller/
    type: attribute

route_accueil:
    path: /accueil
    controller: App\Controller\UtilisateurController::index

mentionsLegales:
    path: /mentionsLegales
    controller: App\Controller\EleveController::ML

#Eleve

route_Eleve:
    path: /eleve/
    controller: App\Controller\EleveController::index

EleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve


#Route Instrument

instrumentListerType:
    path: /instrument/listerType
    controller: App\Controller\InstrumentController::listerTypeInstrument

instrumentConsulterType:
    path: /instrument/consulterType/{id}
    controller: App\Controller\InstrumentController::consulterTypeInstrument

instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument


#Cours

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister


