controllers:
    resource: ../src/Controller/
    type: attribute

route_accueil:
    path: /accueil
    controller: App\Controller\UtilisateurController::index

route_Eleve:
    path: /eleve/
    controller: App\Controller\EleveController::index

EleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve

#Route Instrument

instrumentListerType:
    path: /instrument/listerType
    controller: App\Controller\InstrumentController::listerTypeInstrument

instrumentListerTypeByID:
    path: /instrument/listerType/{id}
    controller: App\Controller\InstrumentController::instrumentListerTypeByID

instrumentConsulterType:
    path: /instrument/consulterType/{id}
    controller: App\Controller\InstrumentController::consulterTypeInstrument

instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument


#Classe Instrument
classeInstrumentLister:
    path: /classeInstrument/lister
    controller: App\Controller\ClasseInstrumentController::lister


#Cours

coursLister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister
