controllers:
    resource: ../src/Controller/
    type: attribute

route_accueil:
    path: /accueil
    controller: App\Controller\UtilisateurController::index

cours_lister:
    path: /cours/lister
    controller: App\Controller\CoursController::lister






app_login:
    path: /login/index
    controller: App\Controller\LoginController::index

Inscription:
    path: /register/inscription
    controller: App\Controller\RegistrationController::register

    # config/routes.yaml
app_logout:
    path: /logout
    methods: GET